# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build jsartoolkit

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: git submodule update --init
    - run: npm install
    - run: docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten-slim:latest bash
    - run: docker exec emscripten npm run build-local
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}  
    - name: Create Release
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v6.0.${{ steps.buildnumber.outputs.build_number }}
        name: Release ${{ steps.buildnumber.outputs.build_number }}
        body: GitHub Actions release
        gzip: true
        files: ./build
